const $ = id => document.getElementById(id);
const states = {todo:'待办',doing:'进行中',done:'已完成'};
const mobile = matchMedia('(max-width: 767px)');
const state = {calendar:null,events:[],handle:null,editingId:null,filterTimer:null};
const addDays=(date,n)=>{const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function announce(message,warning=false){$('statusBanner').textContent=message;$('statusBanner').hidden=!message;$('statusBanner').classList.toggle('warning',warning);}
function filteredEvents(){const q=$('search').value.trim().toLocaleLowerCase(),owner=$('ownerFilter').value,status=$('statusFilter').value;return state.events.filter(row=>!row.deleted_at&&(!q||`${row.title} ${row.body||''} ${row.owner||''}`.toLocaleLowerCase().includes(q))&&(!owner||row.owner===owner)&&(!status||row.status===status));}
function eventToCalendar(row){return{id:row.id,title:row.title,start:row.start_date,end:addDays(row.end_date,1),allDay:true,classNames:[`status-${row.status||'todo'}`],extendedProps:{row}};}
function updateCalendar(){if(!state.calendar)return;state.calendar.removeAllEvents();state.calendar.addEventSource(filteredEvents().map(eventToCalendar));const owners=[...new Set(state.events.map(row=>row.owner).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-CN'));const selected=$('ownerFilter').value;$('ownerFilter').replaceChildren(new Option('所有负责人',''),...owners.map(name=>new Option(name,name)));$('ownerFilter').value=owners.includes(selected)?selected:'';$('syncStatus').textContent=`${filteredEvents().length} 项安排 · ${new Date().toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})} 已更新`;}
function renderCalendar(){state.calendar=new FullCalendar.Calendar($('calendar'),{initialView:mobile.matches?'listMonth':'dayGridMonth',initialDate:today(),timeZone:'UTC',now:()=>`${today()}T00:00:00Z`,firstDay:1,headerToolbar:false,height:'auto',fixedWeekCount:false,locale:{code:'zh-cn',week:{dow:1,doy:4},buttonText:{today:'今天',month:'月',week:'周',list:'日程'},allDayText:'全天',moreLinkText:n=>`＋${n} 更多`,noEventsText:'当前范围暂无工作项'},titleFormat:{year:'numeric',month:'long'},dayMaxEvents:3,editable:!mobile.matches&&!!state.handle,selectable:!mobile.matches&&!!state.handle,datesSet:()=>{if(state.calendar){$('calendarTitle').textContent=state.calendar.view.title;updateViewButtons();}},events:[],dateClick:info=>{if(!mobile.matches&&state.handle)openEditor(null,{start_date:info.dateStr,end_date:info.dateStr});},select:info=>{if(!mobile.matches&&state.handle)openEditor(null,{start_date:info.startStr.slice(0,10),end_date:addDays(info.endStr.slice(0,10),-1)});state.calendar.unselect();},eventClick:info=>{const row=info.event.extendedProps.row;if(!mobile.matches&&state.handle)openEditor(row);else showReadOnly(row);},eventDrop:persistDrag,eventResize:persistDrag,eventContent:info=>{const text=document.createElement('span');text.textContent=info.event.title;return{domNodes:[text]};}});state.calendar.render();updateViewButtons();}
function updateViewButtons(){document.querySelectorAll('[data-view]').forEach(button=>{const active=button.dataset.view===state.calendar?.view.type;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});}
function serialize(){return{schema_version:1,updated_at:new Date().toISOString(),events:state.events};}
async function filePermission(request=false){if(!state.handle)return false;let value=await state.handle.queryPermission({mode:'readwrite'});if(value!=='granted'&&request)value=await state.handle.requestPermission({mode:'readwrite'});return value==='granted';}
async function readHandle(){if(!state.handle)return false;try{if(!await filePermission(true)){announce('浏览器尚未授予文件读写权限，请重新连接日历文件。',true);return false;}const data=JSON.parse(await(await state.handle.getFile()).text());if(data?.schema_version!==1||!Array.isArray(data.events))throw new Error('文件格式不正确，请选择版本为 1 的 calendar.json。');state.events=data.events.filter(row=>row&&typeof row.id==='string'&&typeof row.title==='string'&&row.start_date&&row.end_date);updateCalendar();announce(`已连接 ${state.handle.name}。修改保存在本机文件；提交并 push 后团队可查看。`);return true;}catch(error){announce(error.message||'无法读取日历文件。',true);return false;}}
async function connectFile(){if(!('showOpenFilePicker'in window)){announce('此浏览器不支持直接编辑本机文件，请使用最新版 Edge 或 Chrome。',true);return;}try{const[handle]=await window.showOpenFilePicker({multiple:false,excludeAcceptAllOption:true,types:[{description:'团队日历 JSON',accept:{'application/json':['.json']}}]});state.handle=handle;if(await readHandle()){state.calendar.setOption('editable',true);state.calendar.setOption('selectable',true);}}catch(error){if(error.name!=='AbortError')announce(error.message||'连接日历文件失败。',true);}}
async function writeHandle(){if(!await filePermission(true))throw new Error('没有日历文件写入权限，请重新连接文件后再试。');const writable=await state.handle.createWritable();try{await writable.write(`${JSON.stringify(serialize(),null,2)}\n`);await writable.close();}catch(error){await writable.abort().catch(()=>{});throw error;}updateCalendar();announce('已保存到本机日历文件。请在 GitHub 仓库中提交并 push 后完成团队同步。');}
function draftFromForm(){return{title:$('eventTitle').value.trim(),body:$('eventBody').value,owner:$('eventOwner').value.trim(),start_date:$('eventStart').value,end_date:$('eventEnd').value,status:$('eventStatus').value};}
function openEditor(row,draft={}){if(mobile.matches||!state.handle)return;state.editingId=row?.id||null;const value=row||draft;$('eventHeading').textContent=row?'编辑工作项':'新建工作项';$('eventTitle').value=value.title||'';$('eventBody').value=value.body||'';$('eventOwner').value=value.owner||'';$('eventStart').value=value.start_date||today();$('eventEnd').value=value.end_date||value.start_date||today();$('eventStatus').value=value.status||'todo';$('eventError').textContent='';$('deleteEvent').hidden=!row;$('eventDialog').showModal();}
async function saveDraft(event){event.preventDefault();const draft=draftFromForm();if(!draft.title){$('eventError').textContent='请填写标题。';return;}if(draft.end_date<draft.start_date){$('eventError').textContent='结束日期不能早于开始日期。';return;}const index=state.events.findIndex(row=>row.id===state.editingId);if(index<0)state.events.push({id:crypto.randomUUID(),...draft,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});else state.events[index]={...state.events[index],...draft,updated_at:new Date().toISOString()};try{await writeHandle();$('eventDialog').close();}catch(error){$('eventError').textContent=error.message;}}
async function persistDrag(info){const row=state.events.find(item=>item.id===info.event.id);if(!row){info.revert();return;}row.start_date=info.event.startStr.slice(0,10);row.end_date=addDays(info.event.endStr.slice(0,10),-1);row.updated_at=new Date().toISOString();try{await writeHandle();}catch(error){info.revert();announce(error.message,true);}}
async function deleteEvent(){const row=state.events.find(item=>item.id===state.editingId);if(!row||!confirm('将此工作项移入回收站？'))return;row.deleted_at=new Date().toISOString();row.updated_at=row.deleted_at;try{await writeHandle();$('eventDialog').close();}catch(error){$('eventError').textContent=error.message;}}
function showReadOnly(row){$('readTitle').textContent=row.title;$('readDates').textContent=`${row.start_date} 至 ${row.end_date}`;$('readOwner').textContent=`负责人：${row.owner||'未指定'}`;$('readStatus').textContent=`状态：${states[row.status]||states.todo}`;$('readBody').textContent=row.body||'无备注';$('readDialog').showModal();}
async function refresh(){if(state.handle)return readHandle();try{const response=await fetch(`./calendar.json?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`读取日历失败（${response.status}）`);const data=await response.json();if(data.schema_version!==1||!Array.isArray(data.events))throw new Error('日历文件格式不正确。');state.events=data.events;updateCalendar();announce('只读查看模式。电脑编辑请连接你已 pull 的日历仓库中的 calendar.json。');}catch(error){announce(error.message||'读取日历失败。',true);$('syncStatus').textContent='暂时无法读取';}}
renderCalendar();$('connectFile').addEventListener('click',connectFile);$('refreshButton').addEventListener('click',refresh);$('prevButton').addEventListener('click',()=>state.calendar.prev());$('nextButton').addEventListener('click',()=>state.calendar.next());$('todayButton').addEventListener('click',()=>state.calendar.gotoDate(today()));document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>state.calendar.changeView(button.dataset.view)));for(const id of ['ownerFilter','statusFilter'])$(id).addEventListener('change',updateCalendar);$('search').addEventListener('input',()=>{clearTimeout(state.filterTimer);state.filterTimer=setTimeout(updateCalendar,200);});$('eventForm').addEventListener('submit',saveDraft);$('deleteEvent').addEventListener('click',deleteEvent);$('closeEvent').addEventListener('click',()=>$('eventDialog').close());document.querySelector('[data-close-read]').addEventListener('click',()=>$('readDialog').close());mobile.addEventListener('change',()=>{document.documentElement.classList.toggle('mobile-view',mobile.matches);state.calendar.setOption('editable',!mobile.matches&&!!state.handle);state.calendar.setOption('selectable',!mobile.matches&&!!state.handle);if(mobile.matches)state.calendar.changeView('listMonth');});refresh();setInterval(()=>{if(document.visibilityState==='visible')refresh();},60000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh();});

